{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "conformer.fullname" . }}-wildcard-cert
  labels:
    {{- include "conformer.labels" . | nindent 4 }}
spec:
  secretName: {{ include "conformer.fullname" . }}-wildcard-tls
  issuerRef:
    name: {{ .Values.certManager.issuer.name }}
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.domain }}"
    - "*.{{ .Values.domain }}"
{{- end }}
