apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conformer.fullname" . }}-minio-creds
  labels:
    {{- include "conformer.registryLabels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.minio.auth.rootUser | quote }}
  root-password: {{ .Values.minio.auth.rootPassword | quote }}
