apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conformer.fullname" . }}-config
  labels:
    {{- include "conformer.registryLabels" . | nindent 4 }}
data:
  MINIO_ENDPOINT: {{ include "conformer.minioEndpoint" . | quote }}
  MINIO_BUCKET: "modules"
  MINIO_USE_SSL: "false"
  KEYCLOAK_ISSUER: {{ include "conformer.keycloakIssuer" . | quote }}
  KEYCLOAK_JWKS_URL: {{ include "conformer.keycloakJWKS" . | quote }}
  DOMAIN: {{ .Values.domain | quote }}
  LISTEN_ADDR: ":8080"
  {{- if .Values.registryApi.dynamicBuild.enabled }}
  DYNAMIC_BUILD: "true"
  UPSTREAM_REGISTRY: {{ .Values.registryApi.dynamicBuild.upstreamRegistry | quote }}
  {{- end }}
